apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: talentsphere-eks
  region: us-east-1

managedNodeGroups:
  - name: workers
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
